version: "3.9"

services:
  api:
    build: .
    container_name: fastapi-todo
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/todos
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: todos
      DB_USER: postgres
      POSTGRES_PASSWORD: password
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: todo-db
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todos
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: